spring.application.name=evaluation-risque-service

# Fichier env.properties à créer/positionner à la racine du projet depuis env.properties.example
spring.config.import=optional:file:../env.properties

#Logging
# "INFO" : log tous les .info, .warn et .error ; "DEBUG" : log tout ça + les .debug
logging.level.com.medilabosolutions.evaluationrisqueservice=${APP_LOGGING_LEVEL:INFO}

server.port=${EVALUATION_RISQUE_SERVICE_PORT}

medilabo.username=${MEDILABO_USERNAME}
medilabo.password=${MEDILABO_PASSWORD}

patientservice.url=${PATIENT_SERVICE_URL}
notepraticienservice.url=${NOTE_PRATICIEN_SERVICE_URL}

# Configuration du hot reload
spring.devtools.restart.enabled=true
