spring.application.name=note-praticien-service

# Fichier env.properties a creer/positionner a la racine du projet depuis env.properties.example
spring.config.import=optional:file:../env.properties

#Logging
# "INFO" : log tous les .info, .warn et .error ; "DEBUG" : log tout ca + les .debug
logging.level.com.medilabosolutions.notepraticienservice=${APP_LOGGING_LEVEL:INFO}

server.port=${NOTE_PRATICIEN_SERVICE_PORT}

medilabo.username=${MEDILABO_USERNAME}
medilabo.password=${MEDILABO_PASSWORD}

spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT}
spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.username=${MONGODB_USER}
spring.mongodb.password=${MONGODB_PASSWORD}
spring.mongodb.authentication-database=${MONGODB_AUTH_DATABASE}

# Actuator : uniquement /health expose pour le healthcheck Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
