spring.application.name=note-praticien-service

# Fichier env.properties à créer/positionner à la racine du projet depuis env.properties.example
spring.config.import=optional:file:../env.properties

#Logging
# "INFO" : log tous les .info, .warn et .error ; "DEBUG" : log tout ça + les .debug
logging.level.com.medilabosolutions.notepraticienservice=${APP_LOGGING_LEVEL:INFO}

server.port=${NOTE_PRATICIEN_SERVICE_PORT}

medilabo.username=${MEDILABO_USERNAME}
medilabo.password=${MEDILABO_PASSWORD}

spring.datasource.url=${DB_NOTE_PRATICIEN_URL:jdbc:mysql://localhost:3307/note_praticien_service}
spring.datasource.username=${MONGODB_USER}
spring.datasource.password=${MONGODB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# Configuration du hot reload
spring.devtools.restart.enabled=true
