spring.application.name=patient-service

# Fichier env.properties a creer/positionner a la racine du projet depuis env.properties.example
spring.config.import=optional:file:../env.properties

#Logging
# "INFO" : log tous les .info, .warn et .error ; "DEBUG" : log tout ca + les .debug
logging.level.com.medilabosolutions.patientservice=${APP_LOGGING_LEVEL:INFO}

server.port=${PATIENT_SERVICE_PORT}

medilabo.username=${MEDILABO_USERNAME}
medilabo.password=${MEDILABO_PASSWORD}

spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# Actuator : uniquement /health expose pour le healthcheck Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

# Configuration du hot reload
spring.devtools.restart.enabled=true
