spring.application.name=patient-service

# Fichier env.properties à créer/positionner à la racine du projet depuis env.properties.example
spring.config.import=optional:file:../env.properties

#Logging
# "INFO" : log tous les .info, .warn et .error ; "DEBUG" : log tout ça + les .debug
logging.level.com.medilabosolutions.patientservice=${APP_LOGGING_LEVEL:INFO}

server.port=${PATIENT_SERVICE_PORT}

spring.datasource.url=${DB_PATIENT_URL:jdbc:mysql://localhost:3307/patient_service}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# Configuration du hot reload
spring.devtools.restart.enabled=true
